/**
 *  MIT No Attribution
 *
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of
 *  the Software without restriction, including without limitation the rights to
 *  use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 *  the Software, and to permit persons to whom the Software is furnished to do so.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import { RemovalPolicy } from 'aws-cdk-lib';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import { Construct } from 'constructs';
import { JIRA_ISSUE_INDEX_NAME } from './task-table-indexes';

export { JIRA_ISSUE_INDEX_NAME } from './task-table-indexes';

/**
 * Properties for TaskTable construct.
 */
export interface TaskTableProps {
  /**
   * Optional table name override.
   * @default - auto-generated by CloudFormation
   */
  readonly tableName?: string;

  /**
   * Removal policy for the table.
   * @default RemovalPolicy.DESTROY
   */
  readonly removalPolicy?: RemovalPolicy;

  /**
   * Whether to enable point-in-time recovery.
   * @default true
   */
  readonly pointInTimeRecovery?: boolean;
}

/**
 * DynamoDB table for persisting task state across the agent lifecycle.
 *
 * Schema: task_id (PK) with GSIs for querying by user+status, by status
 * (queue processing), by idempotency key (dedup), and by Jira issue.
 *
 * GSIs:
 * - UserStatusIndex (PK: user_id, SK: status_created_at) — "my tasks" queries
 * - StatusIndex (PK: status, SK: created_at) — queue processing, monitoring
 * - IdempotencyIndex (PK: idempotency_key) — sparse index for dedup
 * - LinearIssueIndex (PK: linear_issue_id, SK: created_at) — sparse; resolve a
 *   Linear issue back to its newest ABCA task + PR (the standalone
 *   comment trigger)
 * - JiraIssueIndex (PK: jira_issue_identity, SK: created_at) — sparse index
 *   for resolving a Jira issue to its newest PR-producing task (#640)
 */
export class TaskTable extends Construct {
  /**
   * GSI name for querying tasks by user and status.
   * PK: user_id, SK: status_created_at (composite: `{status}#{created_at}`).
   */
  public static readonly USER_STATUS_INDEX = 'UserStatusIndex';

  /**
   * GSI name for querying tasks by status.
   * PK: status, SK: created_at.
   */
  public static readonly STATUS_INDEX = 'StatusIndex';

  /**
   * GSI name for idempotency dedup.
   * PK: idempotency_key. Sparse index — only items with the key are projected.
   */
  public static readonly IDEMPOTENCY_INDEX = 'IdempotencyIndex';

  /**
   * GSI name for resolving a Linear issue → its newest ABCA task + PR.
   * PK: linear_issue_id, SK: created_at (newest task wins). Sparse —
   * only Linear-origin tasks (which write the top-level ``linear_issue_id``
   * attribute) are projected; GitHub/Slack/API tasks are absent. Powers the
   * standalone ``@bgagent`` comment trigger on a plain (non-orchestration)
   * issue, where no orchestration row records the issue→PR link.
   */
  public static readonly LINEAR_ISSUE_INDEX = 'LinearIssueIndex';

  /**
   * GSI for resolving a tenant-scoped Jira issue to its newest ABCA task.
   * PK: jira_issue_identity (`{cloudId}#{issueKey}`), SK: created_at.
   */
  public static readonly JIRA_ISSUE_INDEX = JIRA_ISSUE_INDEX_NAME;

  /**
   * The underlying DynamoDB table. Use this to grant access or read the table name.
   */
  public readonly table: dynamodb.Table;

  constructor(scope: Construct, id: string, props: TaskTableProps = {}) {
    super(scope, id);

    this.table = new dynamodb.Table(this, 'Table', {
      tableName: props.tableName,
      partitionKey: {
        name: 'task_id',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      timeToLiveAttribute: 'ttl',
      pointInTimeRecoverySpecification: {
        pointInTimeRecoveryEnabled: props.pointInTimeRecovery ?? true,
      },
      // NEW_IMAGE stream feeds the combined terminal-task reconciler
      // (`OrchestrationReconciler`), which rolls up monthly budget spend and
      // releases dependency-unblocked children. This is deliberately on
      // TaskTable rather than TaskEventsTable, whose stream is already at
      // its 2-consumer limit (FanOutConsumer + ApprovalMetricsPublisher;
      // see TaskEventsTable). It uses one of TaskTable's two DynamoDB Streams
      // consumer slots. NEW_IMAGE contains every field both paths need.
      // Enabling a stream on an existing table is an in-place CFN update
      // (no table replacement).
      stream: dynamodb.StreamViewType.NEW_IMAGE,
      removalPolicy: props.removalPolicy ?? RemovalPolicy.DESTROY,
    });

    // GSI: query tasks by user, optionally filtered by status
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.USER_STATUS_INDEX,
      partitionKey: { name: 'user_id', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'status_created_at', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.ALL,
    });

    // GSI: query tasks by status (for queue processing, monitoring)
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.STATUS_INDEX,
      partitionKey: { name: 'status', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'created_at', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.ALL,
    });

    // GSI: idempotency dedup (sparse — only items with idempotency_key)
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.IDEMPOTENCY_INDEX,
      partitionKey: { name: 'idempotency_key', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.KEYS_ONLY,
    });

    // GSI: Linear issue → newest ABCA task + PR (sparse — only Linear-origin
    // tasks carry the top-level linear_issue_id), for the standalone comment
    // trigger. INCLUDE-projects just the fields the trigger reads, so
    // the index stays lean (no full-item copy on every task write).
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.LINEAR_ISSUE_INDEX,
      partitionKey: { name: 'linear_issue_id', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'created_at', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.INCLUDE,
      // NOTE: a GSI's projection CANNOT be changed in place — DynamoDB rejects it
      // ("Cannot update GSI's properties other than Provisioned Throughput…";
      // observed when deploying the iteration reply). So the iteration reply's
      // running-total query does a per-task GetItem for cost_usd rather than
      // widening this projection. Keep this list as-is unless you create a NEW
      // index with a different name.
      nonKeyAttributes: ['pr_url', 'pr_number', 'status', 'repo', 'user_id', 'channel_metadata'],
    });

    // GSI: Jira issue → newest PR-producing task (#640 comment-triggered PR
    // iteration). Sparse: only Jira-origin tasks with issue metadata carry the
    // top-level jira_issue_identity attribute. Same lean INCLUDE projection as
    // the Linear index above — just the fields the comment-trigger resolver reads.
    this.table.addGlobalSecondaryIndex({
      indexName: TaskTable.JIRA_ISSUE_INDEX,
      partitionKey: { name: 'jira_issue_identity', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'created_at', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.INCLUDE,
      nonKeyAttributes: ['pr_url', 'pr_number', 'status', 'repo', 'user_id', 'channel_metadata'],
    });
  }
}
